### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by piotrekkaminski**
note on vbox - if you don't install/update to the latest you will get weird errors

### CODE REVIEW

**Comment by alankent** [comment]
Thanks. Someone else had similar problems. I am running 17.1 I think (someone failed running version 15)

**Comment by piotrekkaminski** [comment]
i think you are mentioning Vagrant version. I'm talking about VirtualBox version which is 4.x something

**Comment by alankent** [comment]
Virtual box version I am running is 4.3.12.  I cannot use 4.3.20 (latest) on my Windows laptop because the antivirus software seems to interfere with it (lots on the internet about this).

I wanted to put the var (writable) directory inside the box but have not got around to that yet.  Sounds like it might be worthwhile to avoid some file permission problems...

In https://github.com/ryanstreet/magento2-vagrant he does not mount the files off the local file system - just checks them all out within the box I think. This avoids these sorts of file permission problems, but means I have to edit within the box.

**Comment by piotrekkaminski** [comment]
i'm on a Mac which might cause some different experience. Will try Ryan's then.

**Pull request merged**
